Correcciones rubrica 8

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -62,20 +62,41 @@ jobs:
           set +e
           yarn test:unit --coverage || exit_code=$?
           echo "::set-output name=exit_code::$exit_code"
+          mv coverage/lcov-report ./coverage-report
+          echo "exit_code=$exit_code"
           set -e
+      - name: Upload Jest Test Results
+        uses: actions/upload-artifact@v3
+        with:
+          name: jest-results
+          path: coverage-reports/
+
+  jest-validation:
+    needs: unit-integration-tests
+    runs-on: ubuntu-latest
+    if: ${{ needs.unit-integration-tests.outputs.jest_exit_code != '0' }}
+    steps:
       - name: Handle Jest Failure
-        if: ${{ steps.set_exit_code.outputs.exit_code != '0' }}
         run: |
           echo "Jest tests failed. Reverting to previous version..."
           git config --global user.email "20210658@uthh.edu.mx"
           git config --global user.name "rodrigo3829l"
           git reset --hard HEAD^
-          git push origin develop --force
-      - name: Upload Jest Test Results
-        uses: actions/upload-artifact@v3
+          git push origin main --force
+
+  post-coverage-comment:
+    needs: unit-integration-tests
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/github-script@v4
         with:
-          name: jest-results
-          path: coverage/
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `Los reportes de cobertura están disponibles en los artefactos: [Ver artefactos](${{ github.run_id }})`
+            });
 
   sonar-scan:
     needs: unit-integration-tests
@@ -116,13 +137,41 @@ jobs:
       - name: Install Snyk CLI
         run: npm install -g snyk
       - name: Run Snyk Scan
+        id: set_exit_code
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         run: |
-          snyk test --all-projects || exit_code=$?
-          if [ $exit_code -ne 0 ]; then
-            echo "Snyk scan failed. Reverting to previous version..."
-            git config --global user.email "20210658@uthh.edu.mx"
-            git config --global user.name "rodrigo3829l"
-            git reset --hard HEAD^
-            git push origin develop --force
+          set +e
+          snyk monitor --all-projects --org=6ce58cdd-2e65-4c0c-bbe5-705980cee5fe
+          snyk test --all-projects --org=6ce58cdd-2e65-4c0c-bbe5-705980cee5fe || exit_code=$?
+          echo "::set-output name=exit_code::$exit_code"
+          echo "exit_code=$exit_code"
+          set -e
+
+  snyk-validation:
+    needs: snyk-scan
+    if: ${{ needs.snyk-scan.outputs.snyk_exit_code != '0' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Handle Snyk Failure
+        run: |
+          echo "Snyk scan failed. Reverting to previous version..."
+          git config --global user.email "20210658@uthh.edu.mx"
+          git config --global user.name "rodrigo3829l"
+          git reset --hard HEAD^
+          git push origin main --force
+
+  notify-pr:
+    runs-on: ubuntu-latest
+    needs: [unit-integration-tests, snyk-scan, sonar-scan]
+    steps:
+      - uses: actions/github-script@v4
+        with:
+          script: |
+            const status = ${{ needs.unit-integration-tests.outputs.jest_exit_code }} == '0' && ${{ needs.snyk-scan.outputs.snyk_exit_code }} == '0' ? 'Success' : 'Failed';
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `CI/CD Pipeline ${status} for branch ${context.ref}.`
+            });
diff --git a/.github/workflows/feature.yml b/.github/workflows/feature.yml
--- a/.github/workflows/feature.yml
+++ b/.github/workflows/feature.yml
@@ -74,22 +74,43 @@ jobs:
         id: set_exit_code
         run: |
           set +e
-          yarn test:unit || exit_code=$?
+          yarn test:unit --coverage || exit_code=$?
           echo "::set-output name=exit_code::$exit_code"
+          mv coverage/lcov-report ./coverage-report
+          echo "exit_code=$exit_code"
           set -e
-      - name: Handle Jest Failure
-        if: ${{ steps.set_exit_code.outputs.exit_code != '0' }}
-        run: |
-          echo "Jest tests failed. Reverting to previous version..."
-          git config --global user.email "${{ github.ref_name == 'feature/rodrigo' && '20210658@uthh.edu.mx' || '20210667@uthh.edu.mx' }}"
-          git config --global user.name "${{ github.ref_name == 'feature/rodrigo' && 'rodrigo3829l' || 'AvelinaHdez' }}"
-          git reset --hard HEAD^
-          git push origin ${{ github.ref_name }} --force
       - name: Upload Jest Test Results
         uses: actions/upload-artifact@v3
         with:
           name: jest-results
-          path: coverage/
+          path: coverage-reports/
+
+    post-coverage-comment:
+    needs: jest-tests
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/github-script@v4
+        with:
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `Los reportes de cobertura están disponibles en los artefactos: [Ver artefactos](${{ github.run_id }})`
+            });
+
+  jest-validation:
+    needs: jest-tests
+    runs-on: ubuntu-latest
+    if: ${{ needs.unit-integration-tests.outputs.jest_exit_code != '0' }}
+    steps:
+      - name: Handle Jest Failure
+        run: |
+          echo "Jest scan failed. Reverting to previous version..."
+          git config --global user.email "${{ github.ref_name == 'feature/rodrigo' && '20210658@uthh.edu.mx' || '20210667@uthh.edu.mx' }}"
+          git config --global user.name "${{ github.ref_name == 'feature/rodrigo' && 'rodrigo3829l' || 'AvelinaHdez' }}"
+          git reset --hard HEAD^
+          git push origin ${{ github.ref_name }} --force
 
   sonar-scan:
     needs: jest-tests
@@ -138,13 +159,41 @@ jobs:
       - name: Install Snyk CLI
         run: npm install -g snyk
       - name: Run Snyk Scan
+        id: set_exit_code
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         run: |
-          snyk test --all-projects || exit_code=$?
-          if [ $exit_code -ne 0 ]; then
-            echo "Snyk scan failed. Reverting to previous version..."
-            git config --global user.email "${{ github.ref_name == 'feature/rodrigo' && '20210658@uthh.edu.mx' || '20210667@uthh.edu.mx' }}"
-            git config --global user.name "${{ github.ref_name == 'feature/rodrigo' && 'rodrigo3829l' || 'AvelinaHdez' }}"
-            git reset --hard HEAD^
-            git push origin ${{ github.ref_name }} --force
+          set +e
+          snyk monitor --all-projects --org=6ce58cdd-2e65-4c0c-bbe5-705980cee5fe
+          snyk test --all-projects --org=6ce58cdd-2e65-4c0c-bbe5-705980cee5fe || exit_code=$?
+          echo "::set-output name=exit_code::$exit_code"
+          echo "exit_code=$exit_code"
+          set -e
+
+  snyk-validation:
+    needs: snyk-scan
+    if: ${{ needs.snyk-scan.outputs.snyk_exit_code != '0' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Handle Snyk Failure
+        run: |
+          echo "Snyk scan failed. Reverting to previous version..."
+          git config --global user.email "${{ github.ref_name == 'feature/rodrigo' && '20210658@uthh.edu.mx' || '20210667@uthh.edu.mx' }}"
+          git config --global user.name "${{ github.ref_name == 'feature/rodrigo' && 'rodrigo3829l' || 'AvelinaHdez' }}"
+          git reset --hard HEAD^
+          git push origin ${{ github.ref_name }} --force
+
+  notify-pr:
+    runs-on: ubuntu-latest
+    needs: [jest-tests, snyk-scan, sonar-scan]
+    steps:
+      - uses: actions/github-script@v4
+        with:
+          script: |
+            const status = ${{ needs.unit-integration-tests.outputs.jest_exit_code }} == '0' && ${{ needs.snyk-scan.outputs.snyk_exit_code }} == '0' ? 'Success' : 'Failed';
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `CI/CD Pipeline ${status} for branch ${context.ref}.`
+            });
