Main staging

diff --git a/.github/workflows/feature.yml b/.github/workflows/feature.yml
--- a/.github/workflows/feature.yml
+++ b/.github/workflows/feature.yml
@@ -30,23 +30,44 @@ jobs:
   jest-tests:
     needs: lint
     runs-on: ubuntu-latest
+    outputs:
+      jest_exit_code: ${{ steps.set_exit_code.outputs.exit_code }}
     steps:
       - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.MY_GH_TOKEN }}
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '20'
+      - name: Install dependencies
+        run: yarn install
       - name: Run Jest Tests
+        id: set_exit_code
         run: |
+          set +e
           yarn test:unit || exit_code=$?
-          if [ $exit_code -ne 0 ]; then
-            echo "Jest tests failed. Reverting to previous version..."
-            git config --global user.email "${{ github.ref_name == 'feature/rodrigo' && '20210658@uthh.edu.mx' || '20210667@uthh.edu.mx' }}"
-            git config --global user.name "${{ github.ref_name == 'feature/rodrigo' && 'rodrigo3829l' || 'AvelinaHdez' }}"
-            git reset --hard HEAD^
-            git push origin ${{ github.ref_name }} --force
+          echo "::set-output name=exit_code::$exit_code"
+          set -e
+      - name: Handle Jest Failure
+        if: ${{ steps.set_exit_code.outputs.exit_code != '0' }}
+        run: |
+          echo "Jest tests failed. Reverting to previous version..."
+          git config --global user.email "${{ github.ref_name == 'feature/rodrigo' && '20210658@uthh.edu.mx' || '20210667@uthh.edu.mx' }}"
+          git config --global user.name "${{ github.ref_name == 'feature/rodrigo' && 'rodrigo3829l' || 'AvelinaHdez' }}"
+          git reset --hard HEAD^
+          git push origin ${{ github.ref_name }} --force
 
   sonar-scan:
     needs: jest-tests
+    if: ${{ needs.jest-tests.outputs.jest_exit_code == '0' }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.MY_GH_TOKEN }}
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@master
         env:
@@ -55,9 +76,19 @@ jobs:
 
   snyk-scan:
     needs: sonar-scan
+    if: ${{ needs.jest-tests.outputs.jest_exit_code == '0' }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.MY_GH_TOKEN }}
+      - name: Install Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '20'
+      - name: Install dependencies
+        run: yarn install
       - name: Install Snyk CLI
         run: npm install -g snyk
       - name: Run Snyk Scan
@@ -66,7 +97,7 @@ jobs:
         run: |
           snyk test --all-projects || exit_code=$?
           if [ $exit_code -ne 0 ]; then
-            echo "Jest tests failed. Reverting to previous version..."
+            echo "Snyk scan failed. Reverting to previous version..."
             git config --global user.email "${{ github.ref_name == 'feature/rodrigo' && '20210658@uthh.edu.mx' || '20210667@uthh.edu.mx' }}"
             git config --global user.name "${{ github.ref_name == 'feature/rodrigo' && 'rodrigo3829l' || 'AvelinaHdez' }}"
             git reset --hard HEAD^
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -116,7 +116,7 @@ jobs:
           git reset --hard HEAD^
           git push origin main --force
 
-  deploy:
+  deploy-staging:
     needs: snyk-scan
     if: ${{ needs.unit-integration-tests.outputs.jest_exit_code == '0' && needs.snyk-scan.outputs.snyk_exit_code == '0' }}
     runs-on: ubuntu-latest
@@ -148,14 +148,16 @@ jobs:
             set ftp:ssl-protect-list true;
             set ftp:ssl-allow yes;
             open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
-            mirror -R --only-newer --exclude-glob admin --exclude-glob oldcosas --exclude .htaccess ./dist /public_html;
+            mirror -R --only-newer --exclude .htaccess ./dist /public_html/staging;
             quit
           "
 
-  e2e-tests:
-    needs: deploy
+  e2e-tests-staging:
+    needs: deploy-staging
     if: ${{ needs.unit-integration-tests.outputs.jest_exit_code == '0' && needs.snyk-scan.outputs.snyk_exit_code == '0' }}
     runs-on: ubuntu-latest
+    outputs:
+      cypress_exit_code: ${{ steps.set_exit_code.outputs.exit_code }}
     steps:
       - uses: actions/checkout@v3
         with:
@@ -172,10 +174,49 @@ jobs:
           npx cypress run || exit_code=$?
           echo "exit_code=$exit_code" >> $GITHUB_ENV
       - name: Handle Cypress Failure
-        if: env.exit_code != '0'
+        id: set_exit_code
         run: |
-          echo "Cypress tests failed. Reverting to previous version..."
-          git config --global user.email "20210658@uthh.edu.mx"
-          git config --global user.name "rodrigo3829l"
-          git reset --hard HEAD^
-          git push origin main --force
+          set +e
+          npx cypress run || exit_code=$?
+          echo "::set-output name=exit_code::$exit_code"
+          set -e
+      - name: Handle Cypress Failure
+        if: ${{ steps.set_exit_code.outputs.exit_code != '0' }}
+        run: |
+          echo "Cypress tests failed. Skipping production deployment."
+
+    deploy:
+    needs: e2e-tests-staging
+    if: ${{ needs.e2e-tests-staging.outputs.cypress_exit_code == '0' }}
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.MY_GH_TOKEN }}
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '20'
+      - name: Install dependencies
+        run: yarn install
+      - name: Build project
+        run: yarn build
+      - name: Install lftp
+        run: sudo apt-get install lftp
+      - name: Deploy to Hostinger via FTPS (with exclusions)
+        env:
+          FTP_HOST: ${{ secrets.FTP_HOST }}
+          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
+          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
+        run: |
+          lftp -e "
+            set ssl:verify-certificate no;
+            set ftp:ssl-force true;
+            set ftp:ssl-protect-data true;
+            set ftp:ssl-protect-list true;
+            set ftp:ssl-allow yes;
+            open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
+            mirror -R --only-newer --exclude-glob admin --exclude-glob oldcosas --exclude-glob staging --exclude .htaccess ./dist /public_html;
+            quit
+          "
